#!/usr/bin/env python
from high_level import multiples_of, run


run(
    n_good=multiples_of(50, 100, 5),
    n_evil=multiples_of(10, 20, 1),
    has_knowledge=multiples_of(0, 30, 1),
    prob=multiples_of(0, 1, 0.2),
    t=[200],
)
